### ISSUE TITLE
Performance issue.

### ISSUE THREAD

**Issue by Ciao121** [gpac/mp4box.js#141]
Hi,
I'm getting some video infos in this way:
```
var mp4box = new mp4boxModule.MP4Box();
var arrayBuffer = new Uint8Array(fs.readFileSync('video.mp4')).buffer;
arrayBuffer.fileStart = 0;
mp4box.appendBuffer(arrayBuffer);
var videoinfo=mp4box.getInfo()
```
It works fine and I can succesfully get infos I need (videoinfo.audioTracks, videoinfo.subtitleTracks, videoinfo.duration, videoinfo.videoTracks[0].track_width AND videoinfo.videoTracks[0].track_height).

The problem is that if my video file is big it takes a lot of time before getting the info. A 2GB video needs about 20 seconds.

So I'm asking if the one I'm doing it is the correct one or if there's a better and fastest way. Or if someone have any suggestion.
Thank you!!!

**Comment by emmanouil** [comment]
According to the documentation ( https://github.com/gpac/mp4box.js/#getting-information ), in order to get info on a mp4 file, you need to read enough data for the 'moov' box to be parsed, in order for the event to be fired. In the code you display you load the whole file; you can try to progressively load your file instead. In mp4 files it is common for the 'moov' box to be before the 'mdat' (that contains the actual video, in order to be suitable for progressive download / streaming.

**Comment by Ciao121** [comment]
Thank you for your replay. This is absolutely the problem. Now I "only" need to understand how to pass small buffers instead of a huge one to mp4box... :)

**Comment by cconcolato** [comment]
The appendBuffer method takes small buffers. You just have to provide the fileStart property which tells where this small buffer was located in the original (possibly virtual) file. It seems your initial issue is resolved. Reopen the issue if needed.
