### ISSUE TITLE
publish latest release to npm repository

### ISSUE THREAD

**Issue by darbs** [gpac/mp4box.js#144]
It doesnt appear the latest version is in npm. Npm lists mp4box with version 0.3.15 while the newest one here is listed as 0.3.16.

**Comment by josephfrazier** [comment]
I had the same problem, and decided to fix it in https://github.com/gpac/mp4box.js/pull/148. If you'd like, you can install from github with

    npm install https://github.com/josephfrazier/mp4box.js#8df11350d1f2c1bc1c4e6ec3d6a1e125ef258b4b

**Comment by softbrix** [comment]
Bump!

Latest attempt to update npm didn't succeed. Please try to fix the build or manually deploy since I don't like to have git-revisions in my package files and there are a lot of improvements since v0.3.15.
Last build on travis failed during deploy: https://travis-ci.org/gpac/mp4box.js/builds/526261370

**Comment by cconcolato** [comment]
This should be solved now. npm version is v0.3.19 which matches the latest tagged version here. I will try to publish new versions more often.

**Comment by softbrix** [comment]
Thanks! I think this might close some of the other issues as well.
