### ISSUE TITLE
Demux and get vps sps pps not right

### ISSUE THREAD

**Issue by numberwolf** [gpac/mp4box.js#225]
This is vps by stream analyzer(software)
![image](https://user-images.githubusercontent.com/11828206/102515738-129fd180-40c9-11eb-8f9f-0e8f0596fd3f.png)

This is vps by mp4box.js 
![image](https://user-images.githubusercontent.com/11828206/102515845-3105cd00-40c9-11eb-9c85-df2e79bb5816.png)

Can not decode and play
![image](https://user-images.githubusercontent.com/11828206/102515905-3fec7f80-40c9-11eb-9eb1-5cff74f6a9fa.png)

File
[

https://user-images.githubusercontent.com/11828206/102516009-5db9e480-40c9-11eb-937e-84468156b90b.mp4

](url)

**Comment by cconcolato** [comment]
I don't know how you construct the `naluVPS` in your `play.js` file, but when I load it in http://localhost:9000/test/filereader.html the data looks correct:![image](https://user-images.githubusercontent.com/1830314/130161862-51c18b0c-508c-4cfd-a1c2-17e6ea7abe21.png)
I think in your code you forget that the VPS array is an array that starts with a number of NAL:
```
for (j=0; j < numOfArrays; j++) {
unsigned int(1) array_completeness;
bit(1) reserved = 0;
unsigned int(6) NAL_unit_type;
unsigned int(16) numNalus;
for (i=0; i< numNalus; i++) {
unsigned int(16) nalUnitLength;
bit(8*nalUnitLength) nalUnit;
}
}
```
That's why your buffers all start with `0,0,0,1`
