### ISSUE TITLE
SIDX parsing issues

### ISSUE THREAD

**Issue by KozhinM** [gpac/mp4box.js#48]
Hi,
I have been trying to integrate mp4box into <a href="https://github.com/Dash-Industry-Forum/dash.js">dash.js</a> project.  I encountered two issues while  trying to parse sidx box:
1. It seems that ref.size property in the following piece of code is calculated incorrectly: 
```
	//file: box-parse.js 
	//method: BoxParser.sidxBox.prototype.parse
	
	ref.size = tmp_32 & 0x8FFFFFFF;
```

I observe that ref.size has negative value. I peeped at the other parsing lib and it seems that a correct formula is:
`ref.size = tmp_32 & 0x7FFFFFFF;`
2. The size of the sidx box appears to be calculated incorrectly. To be more precise: in the code below an initial `size` value seem to be correct, but then it is reduced by `hdr_size`
```
	// file: box.js
	//method: parseOneBox
	
	if (BoxParser[type+"Box"]) {
		box = new BoxParser[type+"Box"](size - hdr_size);		
	} else {
```

Then in it is reduced once again:

```
	// file: box-parse.js
	// method: BoxParser.FullBox.prototype.parseFullHeader
	
	this.size -= 4;
```
For example, for the following media file the first sidx box should have size = 100, instead it is 88:
http://dash.edgesuite.net/dash264/TestCases/1a/sony/DASH_vodaudio_Track5.m4a

**Comment by cconcolato** [comment]
Thanks for the report. 

Item 1 should now be fixed. Stupid bug in a bit operation. I've checked with your file and it does not have negative subsegment durations anymore.

Regarding item 2, it's not really a bug, but it's indeed ugly and not documented. Some boxes require a countdown of the parsed bytes so far to determine if there is more to parse. I use the size field for that, so I start by removing the basic header (i.e. length, type and others if complex box) size hdr_size, but I need to remove 4 additional bytes when parsing a Full Box (version and tag). That's why the box size is not displayed correctly or even has a 0 value after parsing (#49). I should improve that, use an internal size field for parsing and one for property display.

**Comment by cconcolato** [comment]
Item 2 is fixed now on the dev branch
