### ISSUE TITLE
mp3 audio in mp4 container?

### ISSUE THREAD

**Issue by zhuker** [gpac/mp4box.js#78]
i see there's no support for reading '.mp3' audio sample entry
i am no big expert in mp4 container format, but was it done on purpose or just nobody cared to add support?
```
{ prefix: "Audio", 	types: [ "mp4a", "ac-3", "alac", "dra1", "dtsc", "dtse", ,"dtsh", "dtsl", "ec-3", "enca", "g719", "g726", "m4ae", "mlpa",  "raw ", "samr", "sawb", "sawp", "sevc", "sqcp", "ssmv", "twos" ] },
```

**Comment by rbouqueau** [comment]
Related to #72 , see https://github.com/gpac/mp4box.js/issues/72#issuecomment-175722726

**Comment by zhuker** [comment]
I want to contribute code for mp3 support. 
Any best practices?

**Comment by cconcolato** [comment]
Hi,
Thanks for your interest. mp3 was not added simply because it is not listed on the [MP4 Registration Authority Codecs page](http://mp4ra.org/codecs.html). In fact, there are 2 ways to signal mp3 in mp4: 
  - the standard way using MPEG-4 Systems Descriptor with the appropriate object type (see [ISO/IEC 11172-3 or ISO/IEC 13818-3](http://mp4ra.org/object.html)). 
  - the [Quicktime way](https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html#//apple_ref/doc/uid/TP40000939-CH205-BBCGEBEH) using the code point `.mp3`

GPAC supports both but creates Quicktime-compliant file by default, also fine for VLC. I don't know what is the browser support for mp3 in mp4 and whether it's supported at all. What is the use case?

Since the sample entry for mp3 à la QuickTime is simple, there is nothing more to code than the code point to add in the list you mentioned. I've just added it. You should be able to check with this [file](http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/filereader.html?./mp4/counter_french.mp4).

**Comment by mangui** [comment]
Hi @cconcolato 
interesting, I would be curious to know whether Quicktime MP3 in MP4 is supported by MSE.
if it is the case it would be pretty straightforward to support in https://github.com/dailymotion/hls.js

**Comment by zhuker** [comment]
our tests show that mp3 in mp4 container is supported by at least firefox and safari MSE

**Comment by zhuker** [comment]
@cconcolato use case is - we are wrapping mp3 stream in mp4 and feeding that to MSE audio buffer, in chrome plain mp3 frames work, in firefox they dont for some reason

**Comment by mangui** [comment]
@zhuker , great !
did you check with quicktime way ? 
how did you signal the audio codec ? I tried ```audio/mp4;codecs='mp3'``` , it works on FF, but not on Chrome.

**Comment by zhuker** [comment]
exactly the same experience here
FF - "audio/mp4; codecs='mp3'" == mp3 wrapped in mp4
Chrome - "audio/mpeg" == plain old mp3 frames

**Comment by cconcolato** [comment]
@mangui According to my tests, it is not supported at all via MSE (FF47 on W10 or Safari in OSX). Check for yourself:
http://cconcolato.github.io/media-mime-support/#audio/mp4; codecs=".mp3"

**Comment by cconcolato** [comment]
Ok found it. The code point according to Quicktime is `.mp3` which should translate to `codecs=".mp3"` whereas FF supports simply `codecs="mp3"` (no `.`). Oh no ...

**Comment by tchakabam** [comment]
@cconcolato @mangui we have MP3 packaged in MP4 working in Firefox and Safari. 

The browsers advertise simply `audio/mp4` but not the specific codec, it however works very well :)

**Comment by tchakabam** [comment]
(but using our private lib, i might add support here when i find time)

**Comment by tchakabam** [comment]
i did not try with this muxing library, but it works however with our own one: https://github.com/tchakabam/multimedia.js
