### ISSUE TITLE
grunt test doesn't work

### ISSUE THREAD

**Issue by pps83** [gpac/mp4box.js#83]
If I try to `grunt test` I don't get any tests executed:
```
jdoe@ubuntu:~/work/mp4box.js$ grunt test
Running "jshint:files" (jshint) task
>> 202 files lint free.

Running "concat:all" (concat) task
File dist/mp4box.all.js created.

Running "uglify:all" (uglify) task
>> 1 sourcemap created.
>> 1 file created.

Running "concat:simple" (concat) task
File dist/mp4box.simple.js created.

Running "uglify:simple" (uglify) task
>> 1 sourcemap created.
>> 1 file created.

Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 49.0.2623 (Linux 0.0.0)]: Connected on socket kXs6MQhj2Il0UKMxu3Hf with id 70261175
INFO: '[0:00:00.040]', '[XHR]', 'Getting resource at http://127.0.0.1:8080/code/mp4box.js/test/mp4/h264bl.mp4'
Chrome 49.0.2623 (Linux 0.0.0): Executed 0 of 59 SUCCESS (0 secs / 0 secs)
Chrome 49.0.2623 (Linux 0.0.0): Executed 0 of 59 DISCONNECTED (10.008 secs / 0 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.
jdoe@ubuntu:~/work/mp4box.js$ 

```

I'm not sure if 'http://127.0.0.1:8080/code/mp4box.js/test/mp4/h264bl.mp4' could work and how. Perhaps, something wasn't checked in yet?

**Comment by cconcolato** [comment]
Thanks for the report. 

Indeed, `grunt test` does not work. I'm still looking for a proper way to do testing with grunt for: browser-independent code (without MSE) and for browser-specific code (MSE), that can run in continous integration systems like TravisCI or else. Headless testing with PhantomJS does not work because MSE is not supported. Also I wanted to test with several browsers so I started experimenting with karma but did not have time to dig further. If you have any suggestion, that'd be great.

As for the test themselves, I have a set of qunit tests already, mostly for browser independent code, that normally work (open the html page in your browser). 
 * https://github.com/gpac/mp4box.js/blob/master/test/qunit-tests.js is a set of basic tests for the MP4Box object
 * https://github.com/gpac/mp4box.js/blob/master/test/qunit-isofile-tests.js is for the ISOFile object
 * https://github.com/gpac/mp4box.js/blob/master/test/qunit-iso-conformance.js contains tests for reading/writing of MPEG's conformance files
 * https://github.com/gpac/mp4box.js/blob/master/test/qunit-mse-tests.js is a first attempt at using MSE and are the only tests that require an MSE-capable browser

I just need a way to run them in Travis (or else) with simply Node and with multiple browsers.

**Comment by pps83** [comment]
I see that you have some unit tests and I got it working, but I had to manually copy all media files that are used by unit tests. Also, some unit tests do not pass anymore (getInitializationSegment removed). Also, example.html doesn't exist. I assume it's index.html now, it also should use relative links instead of root-relative. To test MSE in browsers karma can be used, it can run code in chrome. Or selenium maybe?..

**Comment by cconcolato** [comment]
I've changed the location of the media files. The tests now use the media files located on our HTTP server. You can still use a localhost version if you want (just need to comment out the localhost part)

I've fixed the getInitializationSegment part.

I've fixed also the use of Karma (with Chrome). The tests are run on Travis and coverage is reported to coveralls.

Will add the other tests to Karma/Travis/Coveralls when I have more time.

**Comment by cconcolato** [comment]
Added more tests to Karma. Added code coverage as well with Istanbul.
