### ISSUE TITLE
Make DASH manifest

### ISSUE THREAD

**Issue by psy21d** [gpac/mp4box.js#86]
Need to make manifest file for use with DASH player(s) (with node.js then I can parse mp4 file(s) and use result pieces with web server) 
Example https://dxr.mozilla.org/mozilla-central/source/dom/media/test/dash/dash-manifest.mpd
Test http://dashif.org/conformance.html
Be good if mp4box can create manifest, use pieces by own mp4box-code itself, with one function "all-in-box". I sure, that code looks simple.
This detail will make mp4box for node.js server much more better and friendly for users.

Now I need to use this project https://github.com/castlabs/dashencrypt for that deal.

**Comment by psy21d** [comment]
Now I found that MP4BOX can create manifest, example

    MP4Box -dash 4000 -frag 4000 -rap -segment-name %s/segment_ \
    -url-template -out <final_manifest>.mpd \
    <input_video_1>.mp4 <…>.mp4 <input_audio_1>.mp4

And not found how to make it with javascript version.

**Comment by rbouqueau** [comment]
I think you self-answered your question: mp4box.js doesn't create dash manifests.

**Comment by psy21d** [comment]
You does not understand me!
I suggest to make this feature in js version, and does not to close this issue.
If we can not create manifest with js version of mp4box, we can not use full specifications used in  console mp4box!
For example, I need an automation on my own server to create manifests and pieces on-the-fly after download file.

Otherwise, why you did not do js mp4box version if it lack such basic things. Your corporation is working with DASH content, as you suggest I need to do manifest manually, or what?
For you it is a simple thing, you work with it.

Please, re-open ticket as sentence.

**Comment by rbouqueau** [comment]
>  I suggest to make this feature in js version, and does not to close this issue.

Ok I have changed the label of this issue accordingly and re-opened.

> If we can not create manifest with js version of mp4box, we can not use full specifications used in console mp4box!

mp4box.js is not a drop-in replacement of mp4box. For that you could build mp4box with a compiler targetting js such as emscripten or cheerp. See below if you need help.

> Your corporation is working with DASH content, as you suggest I need to do manifest manually, or what?
For you it is a simple thing, you work with it.

GPAC is an open-source project made by individual contributors during their free-time or for their own projects. For corporate matters (like a custom developments), please contact GPAC Licensing: www.gpac-licensing.com

Technically it is possible to generate the DASH manifest on-the-fly. Any contribution from people reading this issue is warmly welcomed.

**Comment by psy21d** [comment]
Thank you

**Comment by publicocean0** [comment]
maybe you could use ffmpeg.js for doing it :)

**Comment by cconcolato** [comment]
I think producing manifest should be done separately and not in mp4box.js.
